const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function fail(message, field="request") { const e=new Error(message); e.name="ValidationError"; e.field=field; throw e; }
function obj(v,f){if(!v||typeof v!=="object"||Array.isArray(v))fail(`${f} must be an object`,f);return v;}
function keys(v,a,f){for(const k of Object.keys(v))if(!a.includes(k))fail(`${f}.${k} is not allowed`,`${f}.${k}`);}
function text(v,f,{required=false,max=4000,defaultValue=""}={}){if(v===undefined||v===null||v===""){if(required)fail(`${f} is required`,f);return defaultValue;}if(typeof v!=="string")fail(`${f} must be text`,f);const n=v.trim();if(required&&!n)fail(`${f} is required`,f);if(n.length>max)fail(`${f} must be ${max} characters or fewer`,f);return n;}
function uuid(v,f,required=false){if(v===undefined||v===null||v===""){if(required)fail(`${f} is required`,f);return null;}if(typeof v!=="string"||!UUID_PATTERN.test(v))fail(`${f} must be a UUID`,f);return v;}
function bool(v,f,d=false,required=false){if(v===undefined||v===null){if(required)fail(`${f} is required`,f);return d;}if(typeof v!=="boolean")fail(`${f} must be boolean`,f);return v;}
function integer(v,f,{defaultValue=0,min=-1000,max=100000}={}){if(v===undefined||v===null)return defaultValue;if(!Number.isInteger(v)||v<min||v>max)fail(`${f} must be an integer from ${min} to ${max}`,f);return v;}
function enumVal(v,f,a,d){const n=v??d;if(!a.includes(n))fail(`${f} must be one of: ${a.join(", ")}`,f);return n;}
function metadata(v,f){if(v===undefined||v===null)return{};return obj(v,f);}
const encounterId=a=>uuid(a.encounterId,"arguments.encounterId",true);
const combatantId=a=>uuid(a.combatantId,"arguments.combatantId",true);
const validators={
 create_encounter(a){keys(a,["name","sessionId","status","metadata"],"arguments");return{name:text(a.name,"arguments.name",{required:true,max:240}),sessionId:uuid(a.sessionId,"arguments.sessionId"),status:enumVal(a.status,"arguments.status",["draft","ready"],"draft"),metadata:metadata(a.metadata,"arguments.metadata")};},
 set_encounter_status(a){keys(a,["encounterId","status"],"arguments");return{encounterId:encounterId(a),status:enumVal(a.status,"arguments.status",["draft","ready","active","paused","completed","archived"])};},
 add_combatant(a){keys(a,["encounterId","characterId","npcId","name","initiative","dexterity","hp","maxHp","tempHp","armorClass","hidden","team","legendaryActionsMax","isLairActor","metadata"],"arguments");const characterId=uuid(a.characterId,"arguments.characterId"),npcId=uuid(a.npcId,"arguments.npcId");if(characterId&&npcId)fail("Provide characterId or npcId, not both","arguments");return{encounterId:encounterId(a),characterId,npcId,name:text(a.name,"arguments.name",{max:240}),initiative:integer(a.initiative,"arguments.initiative",{min:-100,max:200}),dexterity:integer(a.dexterity,"arguments.dexterity",{min:0,max:100}),hp:a.hp===null?null:integer(a.hp,"arguments.hp",{defaultValue:0,min:0}),maxHp:a.maxHp===null?null:integer(a.maxHp,"arguments.maxHp",{defaultValue:0,min:0}),tempHp:integer(a.tempHp,"arguments.tempHp",{min:0}),armorClass:a.armorClass===null?null:integer(a.armorClass,"arguments.armorClass",{defaultValue:10,min:0,max:100}),hidden:bool(a.hidden,"arguments.hidden"),team:text(a.team,"arguments.team",{max:100,defaultValue:"neutral"}),legendaryActionsMax:integer(a.legendaryActionsMax,"arguments.legendaryActionsMax",{min:0,max:10}),isLairActor:bool(a.isLairActor,"arguments.isLairActor"),metadata:metadata(a.metadata,"arguments.metadata")};},
 set_initiative(a){keys(a,["combatantId","initiative","dexterity"],"arguments");if(a.initiative===undefined)fail("arguments.initiative is required","arguments.initiative");return{combatantId:combatantId(a),initiative:integer(a.initiative,"arguments.initiative",{min:-100,max:200}),dexterity:integer(a.dexterity,"arguments.dexterity",{min:0,max:100})};},
 advance_turn(a){keys(a,["encounterId"],"arguments");return{encounterId:encounterId(a)};},
 rewind_turn(a){keys(a,["encounterId"],"arguments");return{encounterId:encounterId(a)};},
 apply_damage(a){keys(a,["combatantId","amount","damageType","source"],"arguments");if(a.amount===undefined)fail("arguments.amount is required","arguments.amount");return{combatantId:combatantId(a),amount:integer(a.amount,"arguments.amount",{min:0,max:100000}),damageType:text(a.damageType,"arguments.damageType",{max:100}),source:text(a.source,"arguments.source",{max:500})};},
 heal(a){keys(a,["combatantId","amount","source"],"arguments");if(a.amount===undefined)fail("arguments.amount is required","arguments.amount");return{combatantId:combatantId(a),amount:integer(a.amount,"arguments.amount",{min:0,max:100000}),source:text(a.source,"arguments.source",{max:500})};},
 set_combatant_stats(a){keys(a,["combatantId","hp","maxHp","tempHp","armorClass"],"arguments");const r={combatantId:combatantId(a)};if(a.hp!==undefined)r.hp=integer(a.hp,"arguments.hp",{min:0});if(a.maxHp!==undefined)r.maxHp=integer(a.maxHp,"arguments.maxHp",{min:0});if(a.tempHp!==undefined)r.tempHp=integer(a.tempHp,"arguments.tempHp",{min:0});if(a.armorClass!==undefined)r.armorClass=integer(a.armorClass,"arguments.armorClass",{min:0,max:100});if(Object.keys(r).length===1)fail("At least one combatant stat is required","arguments");return r;},
 add_condition(a){keys(a,["combatantId","condition","details"],"arguments");return{combatantId:combatantId(a),condition:text(a.condition,"arguments.condition",{required:true,max:100}).toLowerCase(),details:metadata(a.details,"arguments.details")};},
 remove_condition(a){keys(a,["combatantId","condition"],"arguments");return{combatantId:combatantId(a),condition:text(a.condition,"arguments.condition",{required:true,max:100}).toLowerCase()};},
 set_concentration(a){keys(a,["combatantId","active","effect","source"],"arguments");return{combatantId:combatantId(a),active:bool(a.active,"arguments.active",false,true),effect:text(a.effect,"arguments.effect",{max:500}),source:text(a.source,"arguments.source",{max:500})};},
 set_reaction(a){keys(a,["combatantId","available"],"arguments");return{combatantId:combatantId(a),available:bool(a.available,"arguments.available",false,true)};},
 record_death_save(a){keys(a,["combatantId","outcome"],"arguments");return{combatantId:combatantId(a),outcome:enumVal(a.outcome,"arguments.outcome",["success","failure","natural-20","natural-1","reset"])};},
 set_legendary_actions(a){keys(a,["combatantId","maximum","remaining"],"arguments");if(a.maximum===undefined)fail("arguments.maximum is required","arguments.maximum");const maximum=integer(a.maximum,"arguments.maximum",{min:0,max:10});const remaining=integer(a.remaining,"arguments.remaining",{defaultValue:maximum,min:0,max:10});if(remaining>maximum)fail("arguments.remaining cannot exceed maximum","arguments.remaining");return{combatantId:combatantId(a),maximum,remaining};},
 set_combatant_visibility(a){keys(a,["combatantId","hidden","active"],"arguments");return{combatantId:combatantId(a),hidden:bool(a.hidden,"arguments.hidden"),active:bool(a.active,"arguments.active",true)};},
};
const descriptions={create_encounter:"Create an encounter.",set_encounter_status:"Change encounter lifecycle status.",add_combatant:"Add a character, NPC, or custom combatant.",set_initiative:"Set initiative and dexterity tie breaker.",advance_turn:"Advance initiative and round state.",rewind_turn:"Rewind initiative and round state.",apply_damage:"Apply damage with temporary-HP absorption.",heal:"Restore HP up to maximum.",set_combatant_stats:"Set HP, temporary HP, maximum HP, or armor class.",add_condition:"Add a condition with optional details.",remove_condition:"Remove a condition.",set_concentration:"Start or end concentration.",set_reaction:"Spend or restore a reaction.",record_death_save:"Record or reset a death save.",set_legendary_actions:"Set legendary action capacity and remaining uses.",set_combatant_visibility:"Hide, reveal, activate, or deactivate a combatant."};
export const encounterToolDefinitions=Object.freeze(Object.keys(validators).map(name=>({name,description:descriptions[name]})));
export function validateEncounterToolRequest(value){const input=obj(value,"body");keys(input,["tool","arguments"],"body");const tool=text(input.tool,"tool",{required:true,max:100});const validate=validators[tool];if(!validate)fail(`Unsupported encounter tool: ${tool}`,"tool");return{tool,arguments:validate(obj(input.arguments??{},"arguments"))};}
